

#pragma once
 
#define WM_TRD_CALTEST_FINISH			(WM_USER+0x401)
#define WM_TRD_CALTEST_PROGRESS_PROC	(WM_USER+0x402)
#define WM_TRD_CALTEST_UpdateSN_PROC	(WM_USER+0x403)
#define WM_TRD_CALTEST_PostFllg_PROC	(WM_USER+0x404)
#define WM_RFDLG_SIZE					(WM_USER+0x405)
#define WM_UPDATEXMLLOSS				(WM_USER+0x406)

