#ifndef  _ERRORCODE_H_H
#define  _ERRORCODE_H_H


#define QLIB_FUNCTION_SUCCESSFUL			  1
// define for Device operation errorcode 
#define DEVICE_SUCCESS  1000
#define DEVICE_OPENDEFAULTSESSION_FAIL  1001
#define DEVICE_OPENCURRENTSESSION_FAIL  1002
#define DEVICE_FINDRES_FAIL  1003
#define DEVICE_WRITE_FAIL  1004
#define DEVICE_READ_FAIL  1005
#define DEVICE_QUERY_FAIL  1006
#define DEVICE_NOTIN_FASTSWITCH 1007
#define DEVICE_1XEVDO_NOTSUPPORT 1008
#define DEVICE_INTEGERITY_NOTRIGHT 1009
#define DEVICE_VECTORSIZE_NOT_ENOUGH 1010
#define DEVICE_IQCAPSIZE_NOT_EQUAL 1011

//Powersupply errorcode
#define ERR_POWER_SUPPLY_WRONG_OUTPUT               9000

// define MT8820 Measure Status errorcode
#define DEVICE_MSTAT_LEVEL_OVER						1512
#define DEVICE_MSTAT_LEVEL_UNDER					1513
#define DEVICE_MSTAT_NOPERFORMED					1514
#define DEVICE_MSTAT_SYNCWORD_NODETECTED			1515
#define DEVICE_MSTAT_ESTABLISH_SYNC					1516
#define DEVICE_MSTAT_SYNC_LOSS						1517
#define DEVICE_MSTAT_NOT_YET_MEASURED				1519
#define DEVICE_MSTAT_TX_MEAS_TIMEOUT				1522
#define DEVICE_MSTAT_RX_MEAS_TIMEOUT				1523



/*

0 Normal termination
2 Level over
3 Level under
4 Measurement cannot be performed
5 Synchronization word cannot be detected
6 Establishing synchronization
7 Synchronization loss
9 Not yet measured
12 Transmission measurement timeout
13 Reception measurement timeout

*/

//-------------------------------------------------------------------------------------------------
//	5 => GSM/EDGE TEST Device Error Code
//------------------------------------------------------------------------------------------------- 
#define ERR_DEVICE_GSMTEST_SET_BAND	     		         5001
#define ERR_DEVICE_GSMTEST_SET_TX_INPUTLEVEL_AUTO		 5002
#define ERR_DEVICE_GSMTEST_SET_RXQUAL_LEVEL				 5003
#define ERR_DEVICE_GSMTEST_SET_BSSIGNAL_BITSTREAM		 5004
#define ERR_DEVICE_GSMTEST_SET_CHANGE_MODE				 5005
#define ERR_DEVICE_GSMTEST_SET_BSSIGNAL_CHAN			 5006
#define ERR_DEVICE_GSMTEST_FETCH_SPECTRUM_SWIT_FDOMAIN	 5007
#define ERR_DEVICE_GSMTEST_FETCH_SPECTRUM_MOD_FDOMAIN	 5008
#define ERR_DEVICE_GSMTEST_FETCH_RXQUAL_BER				 5009
#define ERR_DEVICE_GSMTEST_SET_TO_TEST_MODE				 5010
#define ERR_DEVICE_GSMTEST_SET_BSSIGNAL_LEVEL			 5011
#define ERR_DEVICE_GSMTEST_SET_CONFIG_INIT				 5012
#define ERR_DEVICE_GSMTEST_QUERY_SIGNAL_STATE			 5013
#define ERR_DEVICE_GSMTEST_SET_SIGNAL_ON				 5014
#define ERR_DEVICE_GSMTEST_SET_SIGNAL_MTC				 5015
#define ERR_DEVICE_GSMTEST_SET_PROC_BSSIGNAL_LEVEL		 5016
#define ERR_DEVICE_GSMTEST_SET_RFGEN_FREQ				 5017
#define ERR_DEVICE_GSMTEST_HANDOVER_TARGET				 5018
#define ERR_DEVICE_GSMTEST_SET_PROC_CHAN				 5019
#define ERR_DEVICE_GSMTEST_SET_PROC_SLOT_PCL			 5020
#define ERR_DEVICE_GSMETEST_FETCH_MODGPSK				 5021
#define ERR_DEVICE_GSMTEST_FETCH_NPOW					 5022
#define ERR_DEVICE_GSMTEST_SET_SPECTRUM_INIT			 5023
#define ERR_DEVICE_GSMTEST_SET_RXQUAL_BER				 5024
#define ERR_DEVICE_GSMTEST_FETCH_BURST					 5025
#define ERR_FETCHRXQUALITYBER_TIME_OUT				     5026
#define ERR_DEVICE_GSMTEST_SET_NSUP						 5027
#define ERR_DEVICE_GSMTEST_ENDCALL						 5028

//define WCDMA TEST Device Error Code
#define WCDMATEST_MEASITEM_PASS								6000
#define ERR_DEVICE_WCDMATEST_RSCP_NORECEIVES				6001
#define WCDMATEST_MAXPOWER_OUTOFRANGE						6002
#define WCDMATEST_MINPOWER_OUTOFRANGE						6003
#define WCDMATEST_TARGETPOWER_OUTOFRANGE					6004
#define WCDMATEST_OBW_OUTOFRANGE							6005
#define WCDMATEST_BER_OUTOFRANGE							6006
#define WCDMATEST_SEMASK_OUTOFRANGE							6007
#define WCDMATEST_ILPC_A_OUTOFRANGE							6008
#define WCDMATEST_ILPC_B_OUTOFRANGE							6009
#define WCDMATEST_ILPC_C_OUTOFRANGE							6010
#define WCDMATEST_ILPC_E_OUTOFRANGE							6011
#define WCDMATEST_ILPC_F_OUTOFRANGE							6012
#define WCDMATEST_ILPC_G_OUTOFRANGE							6013
#define WCDMATEST_ILPC_H_OUTOFRANGE							6014
#define WCDMATEST_FER_OUTOFRANGE							6015
#define WCDMATEST_PHASEERR_OUTOFRANGE						6016
#define WCDMATEST_EVM_OUTOFRANGE							6017
#define WCDMATEST_ACLR_OUTOFRANGE							6018
#define WCDMATEST_RSCP_OUTOFRANGE							6019
#define WCDMATEST_ORIGINOFFSET_OUTOFRANGE					6020
#define WCDMATEST_TIMINGERR_OUTOFRANGE						6021
#define WCDMATEST_MAGTDERR_OUTOFRANGE						6022
#define WCDMATEST_PCDERR_OUTOFRANGE							6023


//define CDMA Cal Device Error Code
#define CDMACAL_SETCH								    3001
#define CDMACAL_SETDLPOW								3002
#define CDMACAL_SETCDTP								    3003
#define CDMACAL_FETCHCHPWR						        3004


//define WCDMA Cal Device Error Code

#define WCDMACAL_SETCH								        4001
#define WCDMACAL_SETMAXPOW								    4002
#define WCDMACAL_FETCHRESULTS								4003
#define WCDMACAL_DLSIGON								    4004

#define WCDMACAL_SETSIG								        4050

//defien GSM cal ErrorCode
#define KVCOFAIL									        7000

// define for Phone operation errorcode
#define PHONE_SUCCESS 2000
#define PHONE_CONNECT_FAIL 2001
#define ERR_QLIB_FUNCTION_FAILED 2002;

//define for common errorcode
#define LOSS_NOT_FIND  9000
#define LOSS_SET_FAIL  9001




#endif


