//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SimRFCaltestUI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SIMRFCALTESTUI_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_Setup                       129
#define IDR_MENU1                       130
#define IDD_DIALOG1                     131
#define IDD_MAINPAGE                    133
#define IDD_BASECONFPAGE                134
#define IDD_LOSSCONFIGPAGE              136
#define IDD_ITEMDETAIL                  137
#define IDB_BITMAP1                     147
#define IDC_COMBO1                      1000
#define IDC_BUTTON1                     1001
#define IDC_CONFIG                      1001
#define IDC_BUTTON2                     1002
#define IDC_Title                       1003
#define IDC_LIST1                       1005
#define IDC_LIST2                       1006
#define IDC_LIST3                       1007
#define IDC_SN                          1008
#define IDC_FILESEQPATH                 1009
#define IDC_LOGPATH                     1010
#define IDC_DIAGPORT                    1011
#define IDC_ATPORT                      1012
#define IDC_PASSFAIL                    1012
#define IDC_TIMEELP                     1013
#define IDC_DIAGPORT2                   1014
#define IDC_TESTSET                     1014
#define IDC_DIAGPORT3                   1015
#define IDC_GPIBADDR                    1015
#define IDC_WAITCOM                     1016
#define IDC_TESTSET1                    1017
#define IDC_GPIBADDR1                   1018
#define IDC_SFCTRL                      1019
#define IDC_STOPFAIL                    1020
#define IDC_PLY                         1021
#define IDC_GPIBADDRPLY                 1022
#define IDC_PLY1                        1023
#define IDC_GPIBADDRPLY1                1024
#define IDC_RUNSN                       1025
#define IDC_PLYPORT                     1026
#define IDC_PLYPORT1                    1027
#define IDC_FREQMEAS                    1028
#define IDC_FREQADDR                    1029
#define IDC_MULMEAS                     1030
#define IDC_MULMEASADDR                 1031
#define IDC_DB                          1032
#define IDC_LOOPCOUNT                   1033
#define IDC_PLY2                        1034
#define IDC_BTLOWCH                     1035
#define IDC_BTMIDCH                     1036
#define IDC_BTHIGHCH                    1037
#define IDC_WLLOWCH                     1038
#define IDC_WLMIDCH                     1039
#define IDC_WLHIGHCH                    1040
#define IDC_DTVLOWCH                    1041
#define IDC_DTVMIDCH                    1042
#define IDC_DTVHIGHCH                   1043
#define IDC_GPSLOWCH                    1044
#define IDC_BTLOWLOSS                   1045
#define IDC_BTMIDLOSS                   1046
#define IDC_BTHIGHLOSS                  1047
#define IDC_BTLOW2                      1048
#define IDC_BTLOW3                      1049
#define IDC_BTLOW4                      1050
#define IDC_BTLOW5                      1051
#define IDC_BTLOW6                      1052
#define IDC_BTLOW7                      1053
#define IDC_BTLOW8                      1054
#define IDC_WLLOWLOSS                   1055
#define IDC_WLMIDLOSS                   1056
#define IDC_WLHIGHLOSS                  1057
#define IDC_DTVLOWLOSS                  1058
#define IDC_DTVMIDLOSS                  1059
#define IDC_DTVHIGHLOSS                 1060
#define IDC_GPSLOWLOSS                  1061
#define IDC_BUTTON3                     1062
#define IDC_GPSLOWCH2                   1063
#define IDC_BUTTON5                     1064
#define IDC_BUTTON6                     1065
#define IDC_PLALL                       1066
#define IDC_PLEN                        1067
#define IDC_BUTTON7                     1068
#define IDC_BUTTON8                     1069
#define IDC_BUTTON9                     1070
#define IDC_BUTTON4                     1071
#define IDC_BUTTON10                    1072
#define IDC_PSW                         1072
#define IDC_PSW_STA                     1073
#define IDC_GPSHIGHLOSS                 1075
#define IDC_TAB4                        1078
#define IDSHOWDETAIL                    1079
#define IDC_ITEMNAME                    1087
#define IDC_EDIT1                       1088
#define IDC_SNEDIT                      1088
#define IDC_GROUPTRACE                  1089
#define IDC_ITEMLIST                    1090
#define IDC_FACLOG                      1091
#define IDC_RADIO1                      1092
#define IDC_CHECK1                      1093
#define IDC_CHECK2                      1094
#define IDC_PROGRESS2                   1096
#define IDC_PRONAME                     1097
#define IDC_PICMAIN                     1101
#define IDC_LOOPCOUNTER                 1102
#define IDC_PASSFAILBIG                 1103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
